"""vulture whitelist: names that exist for features not wired yet.

Generated with ``vulture src --min-confidence 60 --make-whitelist`` and reviewed by
hand. Every entry is a port method or parameter, a ``Dependencies`` member, or a
domain field that a roadmap item (1-4) will use; nothing here is dead code of the
wired audio stage. Remove an entry when its feature reads it, then regenerate.
"""

_.video_frames  # unused method (src/scenewise/adapters/media/ffmpeg.py:136)
vad  # unused variable (src/scenewise/app/deps.py:24)
lid  # unused variable (src/scenewise/app/deps.py:25)
recognizer  # unused variable (src/scenewise/app/deps.py:26)
images  # unused variable (src/scenewise/app/deps.py:35)
notifier  # unused variable (src/scenewise/app/deps.py:40)
container  # unused variable (src/scenewise/domain/inputs.py:21)
init_uri  # unused variable (src/scenewise/domain/inputs.py:22)
rendition  # unused variable (src/scenewise/domain/inputs.py:38)
interval  # unused variable (src/scenewise/domain/inputs.py:54)
uri_template  # unused variable (src/scenewise/domain/inputs.py:68)
interval  # unused variable (src/scenewise/domain/inputs.py:70)
start_offset  # unused variable (src/scenewise/domain/inputs.py:71)
sheets  # unused variable (src/scenewise/domain/inputs.py:78)
grid  # unused variable (src/scenewise/domain/inputs.py:79)
interval  # unused variable (src/scenewise/domain/inputs.py:80)
start_offset  # unused variable (src/scenewise/domain/inputs.py:81)
url  # unused variable (src/scenewise/domain/jobs.py:57)
auth  # unused variable (src/scenewise/domain/jobs.py:58)
key_id  # unused variable (src/scenewise/domain/jobs.py:59)
audience  # unused variable (src/scenewise/domain/jobs.py:60)
visual  # unused variable (src/scenewise/domain/jobs.py:77)
callback  # unused variable (src/scenewise/domain/jobs.py:79)
existing_digest  # unused variable (src/scenewise/domain/jobs.py:150)
model_id  # unused variable (src/scenewise/domain/labels.py:10)
preprocess  # unused variable (src/scenewise/domain/labels.py:11)
cosines  # unused variable (src/scenewise/domain/labels.py:12)
score_transform  # unused variable (src/scenewise/domain/labels.py:13)
embeddings  # unused variable (src/scenewise/domain/labels.py:14)
end_hint  # unused variable (src/scenewise/domain/results.py:24)
log_prob  # unused variable (src/scenewise/domain/results.py:25)
span  # unused variable (src/scenewise/domain/results.py:32)
tokens  # unused variable (src/scenewise/domain/results.py:33)
system  # unused variable (src/scenewise/domain/results.py:40)
prompt  # unused variable (src/scenewise/domain/results.py:41)
json_schema  # unused variable (src/scenewise/domain/results.py:42)
max_tokens  # unused variable (src/scenewise/domain/results.py:43)
model  # unused variable (src/scenewise/domain/results.py:51)
refused  # unused variable (src/scenewise/domain/results.py:52)
score  # unused variable (src/scenewise/domain/results.py:60)
scores  # unused variable (src/scenewise/domain/results.py:68)
report  # unused variable (src/scenewise/domain/results.py:97)
hop  # unused variable (src/scenewise/domain/speech.py:16)
language  # unused variable (src/scenewise/domain/speech.py:24)
probability  # unused variable (src/scenewise/domain/speech.py:25)
dominant  # unused variable (src/scenewise/domain/speech.py:32)
detected  # unused variable (src/scenewise/domain/speech.py:33)
vtt_timestamp  # unused function (src/scenewise/domain/time.py:41)
_.video_frames  # unused method (src/scenewise/ports.py:90)
_.speech_probabilities  # unused method (src/scenewise/ports.py:116)
_.identify  # unused method (src/scenewise/ports.py:124)
windows  # unused variable (src/scenewise/ports.py:125)
_.transcribe  # unused method (src/scenewise/ports.py:134)
language  # unused variable (src/scenewise/ports.py:135)
segments  # unused variable (src/scenewise/ports.py:135)
_.generate  # unused method (src/scenewise/ports.py:144)
_.score  # unused method (src/scenewise/ports.py:152)
_.score  # unused method (src/scenewise/ports.py:160)
prompts  # unused variable (src/scenewise/ports.py:163)
embeddings  # unused variable (src/scenewise/ports.py:165)
_.notify  # unused method (src/scenewise/ports.py:174)
callback  # unused variable (src/scenewise/ports.py:174)
idempotency_key  # unused variable (src/scenewise/ports.py:174)
_._timing  # unused method (src/scenewise/service/config.py:56)
create_app  # unused function (src/scenewise/service/http/app.py:23)
PREREQUISITES  # unused variable (src/scenewise/domain/plan.py:19); read by the dependency_failed rule of item 1 (review r1, finding 13)
